version: "3"

services:

  leader:
    image: python:slim
    container_name: leader
    volumes:
      - ./:/dlock
    working_dir: /dlock
    command: [ "python","leader.py","0.0.0.0","8001","0.0.0.0","8000" ]
    ports:
    - 8001:8001
    - 8000:8000

  follower_1:
    image: python:slim
    container_name: follower_1
    volumes:
      - ./:/dlock
    working_dir: /dlock
    command: [ "python","follower.py","0.0.0.0","8002","leader","8000" ]
    depends_on:
      - leader
    ports:
    - 8002:8002

  follower_2:
    image: python:slim
    container_name: follower_2
    volumes:
      - ./:/dlock
    working_dir: /dlock
    command: [ "python","follower.py","0.0.0.0","8003","leader","8000" ]
    depends_on:
      - leader
    ports:
    - 8003:8003
